markdown: kramdown 
theme: minima
title: Welcome to my homepage!
description: Here I want to share the topics I am most passionate about
owner: 
  name: Britta Rude 
permalink: /blog/:year/:month/:day/:title
google_analytics: G-HP9FYEDLCW
plugins:
  - jekyll-feed
  - jekyll-sitemap
  
