theme: minima
title: Welcome to my homepage!
description: Data Science and Inequality - Here I want to share what I am most passionate about.
author: 
  name: Britta Rude
  email: britta.rude@gmx.net
permalink: /blog/:year/:month/:day/:title
google_analytics: UA-186358575-1
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
#header_pages:
# - about.md
# - thecakestory.md
# generate social links in footer
minima: 
  social_links:
    github:   BrittaRude
    linkedin: britta-rude-712301a4
    twitter: BrittaRude
